FROM suse/sles12sp2-docker:latest

# Import the crt file of our private SMT server
ADD http://192.168.101.101/smt.crt /etc/pki/trust/anchors/smt.crt
RUN update-ca-certificates

RUN zypper ref -s
RUN zypper -n in vim apache2 gcc
